### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dami23** [longcw/RoIAlign.pytorch#11]
Hi, thank you for your work and share. The system is ubuntu16.04 with pytorch 0.5.0. When I run ./install.sh, an error: 
dereferencing pointer to incomplete type 'THTensor {aka struct THTensor}'
     const int batch_size = image->size[0];
occurred. I cannot find a solution on google, could you give me a cue to solve this error. Thank you very much!

**Comment by cbasavaraj** [comment]
Hi, 
I have the same error on pytorch 0.4.1. Were you able to solve this?
Thanks

**Comment by dm-druid** [comment]
pytorch 0.3.1 works.

**Comment by cbasavaraj** [comment]
Hi,
I'm not sure what was wrong, but the error disappeared after I reinstalled PyTorch using
`pip install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl`
0.4.1 has been installed when I did:
`pip install torchvision

**Comment by dm-druid** [comment]
Sometimes we don't know why but it works. ╮(╯_╰)╭

**Comment by dongb5** [comment]
I commented the lines corresponding to cpu version files in build.py and it is built without error. Considering I always run deep learning codes with gpu available, it works for me. : )

**Comment by liuboss1992** [comment]
Hi, I met with the samp problem as you, and I sloved it by downgradem my pytorch from 0.4.1 to 0.4.0

**Comment by cee1** [comment]
aten/src/TH/generic/THTensor.h
```
// Struct definition moved to THTensor.hpp
 typedef struct THTensor THTensor;
```

aten/src/TH/THTensor.hpp
 ```
struct THTensor
 {
     THTensor(THStorage* storage)
       : refcount_(1)
       , storage_(storage)
       , storage_offset_(0)
       , sizes_{0}
       , strides_{1}
       , is_zero_dim_(false)
       {}
 
     ~THTensor() {
       if (storage_) {
         THStorage_free(storage_);
       }
     }
...
```

Looks like C support is dropped

**Comment by lxtGH** [comment]
Yes, due to the API changes of pytorch. Here is the [PR](https://github.com/longcw/RoIAlign.pytorch/pull/13)

**Comment by gemfield** [comment]
Yes, due to the 0.4.1 API change.

**Comment by jolliibeee** [comment]
> Hi,
> I'm not sure what was wrong, but the error disappeared after I reinstalled PyTorch using
> `pip install http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl`
> 0.4.1 had been installed when I did:
> `pip install torchvision`

thanks, it work for me
