### ISSUE TITLE
Could you please make this  project to support pytorch 1.0?

### ISSUE THREAD

**Issue by TonyDongLB** [longcw/RoIAlign.pytorch#24]
Sorry to bother you, but I'm working on a project need your help, thank you so much!

**Comment by longcw** [comment]
Please check this repo for roialgin with pytorch1.0: https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/maskrcnn_benchmark/csrc

**Comment by TonyDongLB** [comment]
666, thanks!

**Comment by longcw** [comment]
Finally this repo
