### ISSUE TITLE
PyTorch 1.0.0 support

### ISSUE THREAD

**Issue by jjldr** [longcw/RoIAlign.pytorch#29]
Sorry to bother you,
PyTorch 1.0.0 support is available now?

**Comment by meikuam** [comment]
Hi, I made this in my fork for this:
https://github.com/meikuam/RoIAlign.pytorch
I'd very glad if you would to test it.

**Comment by longcw** [comment]
Thanks @meikuam for updating this repo to pytorch 1.0. I just had a chance to check and test the update and it works well.
