### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by simo23** [longcw/RoIAlign.pytorch#3]
Hi, 
thank you very much for this code!

The code works fine for me if  I change the capability of the gpu in make.sh as:

$CUDA_PATH/bin/nvcc -c -o crop_and_resize_kernel.cu.o crop_and_resize_kernel.cu -x cu -Xcompiler -fPIC -arch=**sm_50**

Because I have a GPU with 5.0 capability which is slightly less than sm_52 as you wrote. Maybe it is worth mentioning it in the README to check the cacability of the GPU before building.

**Comment by longcw** [comment]
Already added it :-D

**Comment by simo23** [comment]
Thanks +1:
